# Generated by Django 6.1.2 on 2026-10-07 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workplace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "desk_number",
                    models.PositiveIntegerField(verbose_name="Номер стола"),
                ),
                (
                    "additional_information",
                    models.TextField(
                        blank=True, verbose_name="Дополнительная информация"
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employees.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
        ),
    ]
